name: PaSa_env
channels:
  - conda-forge
dependencies:
  - python=3.9.16  ## specify desired version
  - h5py=3.8.0
  - scipy=1.10.1
  - matplotlib=3.7.1
  - numpy=1.24.3
  - seaborn=0.12.2
  - napari=0.4.17
  - pandas=2.0.1
  - qt= 5.15.8
  - scikit-image=0.19.3
  - dask-image=2023.3.0
  - pathlib=1.0.1
  - pip
  - ipykernel
  - jupyterlab
  ## PyPI packages
  - pip:
    - nd2